{
 "title": "AWS DynamoDB",
 "description": "Visualize AWS DynamoDB metrics",
 "tags": [
  "cloudwatch",
  "monitoringartist",
  "link"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "agg", "label": "Aggregation", "query": "30s,1m,5m,15m,1h,6h,1d,7d,30d" },
   {
    "name": "region",
    "label": "Region",
    "query": {}
   },
   {
    "name": "tablename",
    "label": "TableName",
    "query": {}
   },
   {
    "name": "operation",
    "label": "Operation",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "UserErrors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}}",
     "label": "${PROP('MetricName')}",
     "metricName": "UserErrors",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "SuccessfulRequestLatency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "{{metric}} {{Operation}}",
     "dimensions": { "Operation": "$operation", "TableName": "$tablename" },
     "label": "${PROP('Dim.TableName')} :: ${PROP('Dim.Operation')}",
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ConsumedReadCapacityUnits/ConsumedWriteCapacityUnits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "TableName": "$tablename" },
     "metricName": "ConsumedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "$tablename" },
     "metricName": "ConsumedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ProvisionedReadCapacityUnits/ProvisionedWriteCapacityUnits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "metricName": "ProvisionedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "TableName": "$tablename" },
     "metricName": "ProvisionedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}