{
 "title": "AWS CloudFront",
 "description": "Visualize AWS CloudFront metrics",
 "tags": [
  "Cloudfront",
  "Cloudwatch"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "distributionid",
    "label": "DistributionId",
    "query": "dimension_values(us-east-1, AWS/CloudFront, Requests, DistributionId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ErrorRate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "4xxErrorRate",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "5xxErrorRate",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesDownloaded",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  }
 ]
}