{
 "title": "AWS ALB",
 "description": "Shows AWS Application load balancer metrics from Cloudwatch",
 "tags": [
  "aws",
  "cloudwatch",
  "alb"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "loadbalancer",
    "label": "Load Balancer",
    "query": "dimension_values($region, AWS/ApplicationELB, ActiveConnectionCount, LoadBalancer)"
   }
  ]
 },
 "panels": [
  {
   "title": "Healthy targets",
   "type": "stat",
   "description": "The number of targets that are considered healthy.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "UnHealthy targets",
   "type": "stat",
   "description": "The number of targets that are considered unhealthy.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Consumed LCUs",
   "type": "stat",
   "description": "The number of load balancer capacity units (LCU) used by your load balancer.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "ConsumedLCUs",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTP Response",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Target HTTP Response",
   "type": "timeseries",
   "description": "HTTP response code returned from the targets",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "HTTP 2XX",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "HTTP 2XX",
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "HTTP 3XX",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "HTTP 3XX",
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "HTTP 4XX",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "HTTP 4XX",
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "HTTP 5XX",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "HTTP 5XX",
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ELB HTTP Response",
   "type": "timeseries",
   "description": "HTTP response code returned from the load balancer itself, before it even reached the target",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "HTTP 3XX",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "HTTP 3XX",
     "metricName": "HTTPCode_ELB_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "HTTP 4XX",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "HTTP 4XX",
     "metricName": "HTTPCode_ELB_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "HTTP 5XX",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "HTTP 5XX",
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ELB 500 Errors",
   "type": "timeseries",
   "description": "Common 5XX response code returned by AWS ELB",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "HTTP 500",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "HTTP 500",
     "metricName": "HTTPCode_ELB_500_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "HTTP 502",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "HTTP 502",
     "metricName": "HTTPCode_ELB_502_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "HTTP 503",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "HTTP 503",
     "metricName": "HTTPCode_ELB_503_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "HTTP 504",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "HTTP 504",
     "metricName": "HTTPCode_ELB_504_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "ELB Connections metrics",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Active Connections",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "Active Connections",
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "New Connections",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "New Connections",
     "metricName": "NewConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "Rejected Connections",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "Rejected Connections",
     "metricName": "RejectedConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "Target Errors",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "Target Errors",
     "metricName": "TargetConnectionErrorCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "ELB Request metrics",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Requests Total",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "Requests Total",
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "Non Sticky Requests",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "Non Sticky Requests",
     "metricName": "NonStickyRequestCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "Request Per Target (Avg)",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "Request Per Target (Avg)",
     "metricName": "RequestCountPerTarget",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Processed bytes",
   "type": "timeseries",
   "description": "The total number of bytes processed by the load balancer over IPv4 and IPv6. This count includes traffic to and from clients and Lambda functions, and traffic from an Identity Provider (IdP) if user authentication is enabled.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Processed Bytes",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "Processed Bytes",
     "metricName": "ProcessedBytes",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Target Response Time",
   "type": "timeseries",
   "description": "The time elapsed, in seconds, after the request leaves the load balancer until a response from the target is received",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Processed Bytes",
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "Processed Bytes",
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}